"""empty message

Revision ID: 007d0ae8152a
Revises: c25beaec5859
Create Date: 2022-12-28 10:32:39.246818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '007d0ae8152a'
down_revision = 'c25beaec5859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pharmacy_info', schema=None) as batch_op:
        batch_op.drop_index('ix_pharmacy_info_index')

    op.drop_table('pharmacy_info')
    with op.batch_alter_table('hospital_info', schema=None) as batch_op:
        batch_op.drop_index('ix_hospital_info_index')

    op.drop_table('hospital_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_info',
    sa.Column('index', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dutyaddr', mysql.TEXT(), nullable=True),
    sa.Column('dutydiv', mysql.TEXT(), nullable=True),
    sa.Column('dutydivnam', mysql.TEXT(), nullable=True),
    sa.Column('dutyemcls', mysql.TEXT(), nullable=True),
    sa.Column('dutyemclsname', mysql.TEXT(), nullable=True),
    sa.Column('dutyeryn', mysql.TEXT(), nullable=True),
    sa.Column('dutyetc', mysql.TEXT(), nullable=True),
    sa.Column('dutymapimg', mysql.TEXT(), nullable=True),
    sa.Column('dutyname', mysql.TEXT(), nullable=True),
    sa.Column('dutytel1', mysql.TEXT(), nullable=True),
    sa.Column('dutytel3', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8s', mysql.TEXT(), nullable=True),
    sa.Column('hpid', mysql.TEXT(), nullable=True),
    sa.Column('postcdn1', mysql.TEXT(), nullable=True),
    sa.Column('postcdn2', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lon', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lat', mysql.TEXT(), nullable=True),
    sa.Column('dutyinf', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hospital_info', schema=None) as batch_op:
        batch_op.create_index('ix_hospital_info_index', ['index'], unique=False)

    op.create_table('pharmacy_info',
    sa.Column('index', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dutyaddr', mysql.TEXT(), nullable=True),
    sa.Column('dutyetc', mysql.TEXT(), nullable=True),
    sa.Column('dutyinf', mysql.TEXT(), nullable=True),
    sa.Column('dutymapimg', mysql.TEXT(), nullable=True),
    sa.Column('dutyname', mysql.TEXT(), nullable=True),
    sa.Column('dutytel1', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8s', mysql.TEXT(), nullable=True),
    sa.Column('hpid', mysql.TEXT(), nullable=True),
    sa.Column('postcdn1', mysql.TEXT(), nullable=True),
    sa.Column('postcdn2', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lon', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lat', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pharmacy_info', schema=None) as batch_op:
        batch_op.create_index('ix_pharmacy_info_index', ['index'], unique=False)

    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
