"""empty message

Revision ID: ec2265ffb9e7
Revises: 007d0ae8152a
Create Date: 2022-12-30 17:22:26.157638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec2265ffb9e7'
down_revision = '007d0ae8152a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_info', schema=None) as batch_op:
        batch_op.drop_index('ix_hospital_info_index')

    op.drop_table('hospital_info')
    with op.batch_alter_table('pharmacy_info', schema=None) as batch_op:
        batch_op.drop_index('ix_pharmacy_info_index')

    op.drop_table('pharmacy_info')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('pharmacy_info',
    sa.Column('index', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dutyaddr', mysql.TEXT(), nullable=True),
    sa.Column('dutyetc', mysql.TEXT(), nullable=True),
    sa.Column('dutyinf', mysql.TEXT(), nullable=True),
    sa.Column('dutymapimg', mysql.TEXT(), nullable=True),
    sa.Column('dutyname', mysql.TEXT(), nullable=True),
    sa.Column('dutytel1', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8s', mysql.TEXT(), nullable=True),
    sa.Column('hpid', mysql.TEXT(), nullable=True),
    sa.Column('postcdn1', mysql.TEXT(), nullable=True),
    sa.Column('postcdn2', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lon', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lat', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pharmacy_info', schema=None) as batch_op:
        batch_op.create_index('ix_pharmacy_info_index', ['index'], unique=False)

    op.create_table('hospital_info',
    sa.Column('index', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dutyaddr', mysql.TEXT(), nullable=True),
    sa.Column('dutydiv', mysql.TEXT(), nullable=True),
    sa.Column('dutydivnam', mysql.TEXT(), nullable=True),
    sa.Column('dutyemcls', mysql.TEXT(), nullable=True),
    sa.Column('dutyemclsname', mysql.TEXT(), nullable=True),
    sa.Column('dutyeryn', mysql.TEXT(), nullable=True),
    sa.Column('dutyetc', mysql.TEXT(), nullable=True),
    sa.Column('dutymapimg', mysql.TEXT(), nullable=True),
    sa.Column('dutyname', mysql.TEXT(), nullable=True),
    sa.Column('dutytel1', mysql.TEXT(), nullable=True),
    sa.Column('dutytel3', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8c', mysql.TEXT(), nullable=True),
    sa.Column('dutytime1s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime2s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime3s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime4s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime5s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime6s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime7s', mysql.TEXT(), nullable=True),
    sa.Column('dutytime8s', mysql.TEXT(), nullable=True),
    sa.Column('hpid', mysql.TEXT(), nullable=True),
    sa.Column('postcdn1', mysql.TEXT(), nullable=True),
    sa.Column('postcdn2', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lon', mysql.TEXT(), nullable=True),
    sa.Column('wgs84lat', mysql.TEXT(), nullable=True),
    sa.Column('dutyinf', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hospital_info', schema=None) as batch_op:
        batch_op.create_index('ix_hospital_info_index', ['index'], unique=False)

    # ### end Alembic commands ###
